settings:
  base_path: build
  d_path: build/kernel.us.d
  target_path: build/kernel.us.elf
  partial_build_segments_folder: segments

  sections_allowlist:
    # mips debug sections
    - .pdr
    - .mdebug
    - .mdebug.abi32
  sections_denylist:
    - .reginfo
    - .MIPS.abiflags
    - .MIPS.options
    - .note.gnu.build-id
    - .interp
    - .eh_frame
  discard_wildcard_section: True

  segment_start_align: 0x10
  segment_end_align: 0x10
  # Required for matching
  section_end_align: 0x10

  wildcard_sections: True

segments:
  - name: boot
    fixed_vram: 0x80000450
    files:
      - { path: src/1050.o }
      - { path: src/17E0.o }
      - { path: src/clocks.o }
      - { path: src/1F60.o }
      - { path: src/filesystem.o }
      - { path: src/memory.o }
      - { path: src/3630.o }
      - { path: src/3F10.o }
      - { path: src/unused_props.o }
      - { path: src/sched.o }
      - { path: src/main.o }
      - { path: src/unused.o }
      - { path: asm/us/mio0Decode.o }
      - { path: asm/us/setintmask.o }
      - { path: asm/us/getcount.o }
      - { path: asm/us/62E0.o }
      - { path: asm/us/data/1A930.data.o }
      - { path: asm/us/data/21B00.rodata.o }
      - { path: asm/us/data/21C70.rodata.o }
      - { path: asm/us/data/bss_1.bss.o }
      - { path: asm/us/data/bss_2.bss.o }
      - { path: asm/us/data/bss_3.bss.o }
      - { path: asm/us/data/bss_4.bss.o }
      - { path: src/mem_block.o }
