import subprocess
import sys
import os
from pathlib import Path

PATCHED_MODULE_FILES_DIR = "patched_modules"

moduleFiles = [
    "ai.bin",
    "aiedit.bin",
    "airec.bin",
    "battle.bin",
    "bubble.bin",
    "cam.bin",
    "caranim.bin",
    "caraudio.bin",
    "cbars.bin",
    "dledit.bin",
    "demo.bin",
    "env.bin",
    "envsnd.bin",
    "expl.bin",
    "filerom.bin",
    "fileux.bin",
    "filmroll.bin",
    "flag.bin",
    "game.bin",
    "gamegui.bin",
    "glare.bin",
    "intro.bin",
    "letter.bin",
    "level1.bin",
    "light.bin",
    "logo.bin", # OK
    "med.bin",
    "menuslct.bin",
    "misc.bin",
    "motion.bin",
    "mult1.bin",
    "mult2.bin",
    "mult3.bin",
    "mult4.bin",
    "mult5.bin",
    "mult6.bin",
    "mult7.bin",
    "mult8.bin",
    "mult9.bin",
    "pause.bin",
    "piece.bin",
    "plyr.bin",
    "powerup.bin",
    "profgame.bin",
    "race.bin",
    "rain.bin",
    "replay.bin",
    "results.bin",
    "ripple.bin",
    "rumble.bin",
    "scene.bin",
    "scrn.bin",
    "selection.bin",
    "shadow.bin",
    "skid.bin",
    "smack.bin",
    "snd.bin",
    "sparks.bin",
    "splash.bin",
    "spray.bin",
    "tdata.bin",
    "ted.bin",
    "track1.bin",
    "track2.bin",
    "track3.bin",
    "track4.bin",
    "track5.bin",
    "track6.bin",
    "track7.bin",
    "triganim.bin",
    "txtview.bin",
    "ufo.bin",
    "ufogame.bin",
    "voltest.bin",
    "weapon.bin",
    "uvaudiomgr_rom.bin",
    "uvbill_rom.bin",
    "uvblit_rom.bin",
    "uvcback_rom.bin",
    "uvcmidi_rom.bin",
    "uvchannel_rom.bin",
    "uvcolor_rom.bin",
    "uvcont_rom.bin",
    "uvcontourld_rom.bin",
    "uvdgeom_rom.bin",
    "uvdbg_rom.bin",
    "uvdobj_rom.bin",
    "uvdsetld_rom.bin",
    "uvdyn_rom.bin",
    "uvear_rom.bin",
    "uvemitter_rom.bin",
    "uvenv_rom.bin",
    "uvenvld_rom.bin",
    "uvfmtx_rom.bin",
    "uvfvec_rom.bin",
    "uvfont_rom.bin",
    "uvfontld_rom.bin",
    "uvfx_rom.bin",
    "uvgeom_rom.bin",
    "uvgfxmgr_rom.bin",
    "uvgfxstate_rom.bin",
    "uvgrph_rom.bin",
    "uvgui_rom.bin",
    "uvimtx_rom.bin",
    "uvintersect_rom.bin",
    "uvisect_rom.bin",
    "uvjanim_rom.bin",
    "uvjanimld_rom.bin",
    "uvled_rom.bin",
    "uvlight_rom.bin",
    "uvmath_rom.bin",
    "uvmodel_rom.bin",
    "uvmodelld_rom.bin",
    "uvpfx_rom.bin",
    "uvpfxld_rom.bin",
    "uvquat_rom.bin",
    "uvquery_rom.bin",
    "uvsort_rom.bin",
    "uvsprt_rom.bin",
    "uvstring_rom.bin",
    "uvtexanim_rom.bin",
    "uvtseq_rom.bin",
    "uvtseqld_rom.bin",
    "uvterra_rom.bin",
    "uvterrald_rom.bin",
    "uvtexture_rom.bin",
    "uvtexturexref_rom.bin",
    "uvtextureld_rom.bin",
    "uvtrackld_rom.bin",
    "uvufileld_rom.bin",
    "uvvattr_rom.bin",
    "uvvolumeld_rom.bin",
    "victory.bin",
]

def makePatchedModuleFilesDir():
    Path(PATCHED_MODULE_FILES_DIR).mkdir(exist_ok=True)


def genRelocsAndSymsFiles():
    for module in moduleFiles:
        print("Processing:", module)
        subprocess.run(
            [
                "./module_tool",
                "bin/us/" + module,
                "-a",
                "-s",
                "-w",
                "-o",
                PATCHED_MODULE_FILES_DIR + "/" + module,
            ],
            check=True,
        )

makePatchedModuleFilesDir()
genRelocsAndSymsFiles()
