import sys

def writeKernelLinkerScript(list, path):
    with open(path, 'w', encoding='utf-8', newline='\n') as file:
        # First line
        for line in list:
            file.write(line + '\n')
            

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Gen kernel linker script <romLinkerScript.ld>")
        sys.exit(1)
    
    kernelLinkScriptLines = []
    kernelLinkScriptLines.append('/* Autogenerated by genKernelLd */')

    with open(sys.argv[1], "r") as file:
        for line in file:
            processed_line = line.strip()
            kernelLinkScriptLines.append(processed_line)
            if (processed_line.find("FORM0_VRAM_END") != -1):
                break

    kernelLinkScriptLines.append('/DISCARD/ :\n')
    kernelLinkScriptLines.append('{\n')
    kernelLinkScriptLines.append('*(*);\n')
    kernelLinkScriptLines.append('}\n')
    kernelLinkScriptLines.append('}\n')

    writeKernelLinkerScript(kernelLinkScriptLines, "linker_scripts/us/kernel.ld")

