.include "macro.inc"

.section .data

.align 4

/* Generated by spimdisasm 1.40.0 */

nonmatching D_004002D0

dlabel D_004002D0
    /* 000304 00000304 01000000 */ .word 0x01000000
    /* 000308 00000308 000C0000 */ .word 0x000C0000
    /* 00030C 0000030C 00000000 */ .word __entrypoint_func_logo_400000
    /* 000310 00000310 00000000 */ .word 0x00000000
enddlabel D_004002D0
