.include "macro.inc"

.section .bss

.align 4

/* Generated by spimdisasm 1.40.0 */

nonmatching B_004002E0, 0x8

dlabel B_004002E0
    /* 00000314 */ .space 0x08

nonmatching D_4002E8, 0x8

dlabel D_4002E8
    /* 0000031C */ .space 0x08
